### ISSUE TITLE
Add array.push and array.splice tests

### ISSUE THREAD

**Issue by miyconst** [Juicy/dom-bind-notifier#1]
There should be automated tests for:

1. `dom-repeat` should add row after `array.push({})`.
2. `dom-repeat` should insert row after `array.splice(1, 0, {})`.
3. `dom-repeat` should change the #1 item after `array.splice(1, 0, {}); array[1].value = "new value"`.

**Comment by miyconst** [comment]
There are already tests for adding array items with `array.push` & `array.splice`, I have added a test for the point 3.

**Comment by tomalec** [comment]
It seems to be an issue with Polymer `notifySplice` or `dom-repeat` as even tough it figures out array index and collection key properly, it uses `index` as `key`.

**Comment by tomalec** [comment]
Workaround implemented :)
