### ISSUE TITLE
Maximum call stack size exceeded - if array item has reference to the array

### ISSUE THREAD

**Issue by miyconst** [Juicy/dom-bind-notifier#2]
`dom-bind-notifier` causes `Maximum call stack size exceeded` exception if an item of observed array has reference to the array.

```html
<template is="dom-bind" id="root">
    <ul>
        <li><b>Title</b></li>
        <template is="dom-repeat" items="{{model.items}}">
            <li>[[item.name]]</li>
        </template>
    </ul>
    <button type="button" on-click="pushItem">Push item</button>
    <dom-bind-notifier observed-object="{{model}}" ref="root" path="model" deep></dom-bind-notifier>
</template>
```

```js
var t = document.querySelector("#root");
var items = [];

items.push({
	parent: items,
	name: "item 0"
}, {
	parent: items,
	name: "item 1"
}, {
	parent: items,
	name: "item 2"
});

t.model = {
	items: items
};

t.pushItem = function () {
	items.push({
		parent: items,
		name: "item " + items.length
	});

	console.log(t.model.items);
};
```

https://jsfiddle.net/r0c5j5e0/

**Comment by tomalec** [comment]
Hm... seems to be a problem with circular reference in our deep observer. Maybe you can try defining `parent` using define property as non-enumerable.

**Comment by tomalec** [comment]
We can fix the root issue by implementing WeakMap of observed object. The only doubt I have do we really need it, as in most of the cases, we will use this element to stamp JSON - which by definition is non-circular. 

Or maybe we should implement it here, as we plan to write JSON(-Patch) optimized version, which will do not bother about circular stuff at all.

WDYT, @warpech, @miyconst

**Comment by warpech** [comment]
We discussed a similar problem when designing https://github.com/Starcounter-Jack/JSON-Patch

The decision was that JSON-Patch works on JSON and JSON does not allow for circular references. 

Of course, we could make it "aware" of JS objects in addition to JSON, but we decided that it would add unnecessary performance overhead. If you have problem to decide if the data is correct JSON, call `JSON.stringify(items)`.

I think we could make a similar assumption to dom-bind-notifier, if it is practical enough. For our use case with Puppet, I think that such limitation would be ok, wouldn't it?

**Comment by miyconst** [comment]
That sounds reasonable. I agree with @warpech.

**Comment by tomalec** [comment]
Cool, then I'm closing it as won't fix.

**Comment by warpech** [comment]
And `$parent` in PuppetJS is set not enumberable. It does not break `JSON.stringify` etc
