### ISSUE TITLE
Replacing multiple times, the same node in nested array is not reflected in HTML stamped by Polymer's dom-bind

### ISSUE THREAD

**Issue by tomalec** [Juicy/dom-bind-notifier#4]
Replacing element in nested array, gets reflected in stamped DOM only once.
```js
model.path_to.array[0].nested_array[0] = {prop: "firstChange"};
// gets reflected
model.path_to.array[0].nested_array[0] = {prop: "secondChange"};
// nothing happens
```

May be related to https://github.com/Juicy/dom-bind-notifier/issues/3

**Comment by tomalec** [comment]
seems to be an issue with Polymer's `notifyPath` and `Polymer.Collection` 
https://github.com/Polymer/polymer/issues/2540

**Comment by warpech** [comment]
Nice catch! Will you update `/sys/`?

**Comment by miyconst** [comment]
@tomalec thank you once again for the great job.

**Comment by miyconst** [comment]
I have updated `/sys/` folder.
