### ISSUE TITLE
Object.observe is dead

### ISSUE THREAD

**Issue by miyconst** [Juicy/dom-bind-notifier#6]
As stated in issue: https://github.com/Starcounter-Jack/JSON-Patch/issues/82 `Object.observe` is no longer supported. 

`dom-bind-notifier` depends on this feature, so we should either include shim as a required dependency or somehow use the `JSON-Patch` to get notified about the changes.

**Comment by warpech** [comment]
We are safe when we switch to https://github.com/Starcounter/Starcounter/issues/2922

**Comment by miyconst** [comment]
For now we are using this shim:
https://github.com/MaxArt2501/object-observe
https://github.com/MaxArt2501/array-observe

And `puppet-dom-bind-notifier` has it's own issue. Closing this one.
